# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=1.1.0+mc26.2-port.2
maven_group=com.github.therongdd
archives_base_name=BalancedStackSizes
# Dependencies
fabric_version=0.158.0+26.2
owo_version=0.13.1+26.2
